- AERA/replicode_v1.2/hand-grab-sphere-learn.replicode
- AERA/replicode_v1.2/hand-grab-sphere.replicode
- License.txt
- doc/meeting-notes.txt
In hand-grab-sphere model `M0`, simulated backward chaining matches a goal position P1 on the RHS and computes a DeltaP for the LHS move command based on the current position P0.
M0:(mdl [H: P0: T0: T1:] []
(fact (cmd move [H: DeltaP:] :) T2: T1_cmd: : :)
(fact (mk.val H: position P1: :) T1_RHS: T3: : :))
It is possible that backward chaining can derive a subgoal for a position P1 (based on other criteria) which is the same as the current position P0. In this case the DeltaP for the move command would be 0. During simulated forward chaining, this can add one or more steps to simulate a move of 0 which doesn't change any state variables. It only adds unnecessary steps to the simulation. In general, a command should only be executed that changes the state. This pull request updates the …
> hand-grab-sphere: Make M0 require change

- r_exec/mdl_controller.cpp
Background: During simulated chaining, `retrieve_simulated_imdl_bwd` matches a stored simulated requirement to a goal requirement. If a model has both strong and weak requirements, then during simulated forward chaining `retrieve_simulated_imdl_bwd` first [finds a matching strong requirement](https://github.com/IIIM-IS/AERA/blob/c2887c08f1548a33b565326627910f59af086b14/r_exec/mdl_controller.cpp#L743-L767) ("negative" requirement). Then it finds a matching weak requirement ("positive" requirement) and uses it if its confidence is [greater than the strong requirement](https://github.com/IIIM-IS/AERA/blob/c2887c08f1548a33b565326627910f59af086b14/r_exec/mdl_controller.cpp#L784). Otherwise the strong requirement "disables" the weak requirement. But it does not check the timings of the strong …
> Don't let old strong requirement disable a weak requirement

- r_exec/factory.h
- r_exec/mdl_controller.cpp
- r_exec/mdl_controller.h
Pull request #182 added support for `DefeasibleValidity` which is attached to the simulated predicted command that comes from a weak requirement. The `DefeasibleValidity` is attached to all simulated predictions which come from the command. If later in the simulation a strong requirement disables the weak requirement, then the `DefeasibleValidity` is invalidated, which invalidates all the predictions which came from the command.
This works as long as each model has a unique command on its LHS. But if multiple models have the same command on the LHS, then the following scenario is possible. Consider these two models from the Pong example (simplified):
mdl_ball_position_y:(mdl [B: X0: Y0: VX: VY: T0: T1:] []
(fact (cmd tick |[]) T0_cmd: T1_cmd:)
(fact (mk.val B: position_y Y1:) T2: T3:)) …
> Add the defeasible consequence from weak requirements to its predictions

- r_exec/factory.h
- r_exec/mdl_controller.cpp
During simulated forward chaining, when a simulated requirement is attached to a model controller, the existing simulated goal monitors [are signalled](https://github.com/IIIM-IS/AERA/blob/ea6eca6889be8b9a176a04482e23ae781e75427b/r_exec/mdl_controller.cpp#L1541-L1552) which may create a simulated predicted command from the LHS. This can happen multiple times for the same model. There is [existing code](https://github.com/IIIM-IS/AERA/blob/ffcd6ded25a990bd40c53d48cba71ab9bd33164a/r_exec/mdl_controller.cpp#L2102-L2108) to check if the same LHS command has already been signalled and to avoid injecting another identical command. This code does this check separately for each model controller because different models have different requirement and anti-requirement models attached and would be …
> If LHS command is already signalled, update its set of DefeasibleValidities

- AERA/replicode_v1.2/std.replicode
- CHANGELOG.md
- r_code/atom.cpp
- r_code/atom.h
- r_code/atom.inline.cpp
- r_code/code_utils.cpp
- r_comp/compiler.cpp
- r_comp/compiler.h
- r_comp/decompiler.cpp
- r_comp/decompiler.h
- r_comp/preprocessor.cpp
- r_comp/structure_member.cpp
- r_comp/structure_member.h
- r_exec/binding_map.cpp
- r_exec/binding_map.h
- r_exec/context.cpp
- r_exec/context.h
- r_exec/factory.cpp
- r_exec/factory.h
- r_exec/group.cpp
- r_exec/guard_builder.cpp
- r_exec/mdl_controller.cpp
- r_exec/mem.cpp
- r_exec/mem.h
- r_exec/operator.cpp
- r_exec/overlay.cpp
- r_exec/pgm_controller.cpp
This pull request resolves issue #138. It completes the changes started in pull request #205 which added support for the DURATION type in Replicode, but didn't change to use it yet.
This pull request has three commits. The first commit changes the Replicode compiler and Code representations to distinguish duration from time stamp. If the compiler reads a duration constant like `100ms` it is represented in Code as a DURATION. The rest of the AERA code is changed to expect this. For example, the `Sim` method for `get_thz` [is changed](https://github.com/IIIM-IS/AERA/blob/872d69249aecc962e5b7f166563d15d4c25d79f1/r_exec/factory.h#L242-L244) to use `GetDuration` instead of `GetTimestamp`. The compiler also adds support for `ts` to specify in `std.replicode` that a parameter is a time stamp. …
> Add duration to Replicode syntax

- r_comp/compiler.cpp
In Replicode, here is a statement to print `"start: Inject fact"`:
(prb [1 "print" "start: Inject fact" |[]])
However, the compiler prints the confusing message "error: no variables allowed outside a pattern skeleton". This is because it treats `"start` as a symbol which is followed by `:` and so it thinks it is a variable. The problem comes from [symbol_expr](https://github.com/IIIM-IS/AERA/blob/f8317c20d0af85553b6d44f2c70018f9cf1dbb7e/r_comp/compiler.cpp#L544-L581) which checks if a sequence of characters is a symbol. 
This pull request updates `symbol_expr` to exclude `"` as a symbol character. Therefore the start of the string is not a symbol and not treated as a variable. Now the message is printed as expected.
> Compiler: Don't allow string as symbol so it doesn't restrict characters

- AERA/replicode_v1.2/std.replicode
- AERA/replicode_v1.2/user.classes.replicode
`user.classes.replicode` loads `std.replicode` which defines groups like `primary`. These are defined in `std.replicode` like this using `std_grp`:
primary:(std_grp 2 0 0.4 0 |[])
Even though `std_grp` is used in `std.replicode`, the `!def` for it is in `user.classes.replicode`. This works because Replicode first runs a preprocessor on all the `!def`, then uses them. So it is possible for a `!def` to appear after it is used. But this is counter-intuitive. This pull request moves the `!def` for `std_grp` from `user.classes.replicode` to `std.replicode`.
> Move definition of std_grp to std.replicode

- r_exec/mdl_controller.cpp
Currently, during simulated backward chaining, it is possible for a goal to have an "opposite" match to a RHS. In this case, the `abduce` method [sets the simulation mode](https://github.com/IIIM-IS/AERA/blob/47787aef06286d0d289be23252500b83d851f828/r_exec/mdl_controller.cpp#L1846) to `SIM_MANDATORY`:
case SIM_ROOT:
sub_sim = new Sim(opposite ? SIM_MANDATORY : SIM_OPTIONAL, sim_thz, super_goal, opposite, ...);
Note that it does this when backward chaining first begins at the root. But it is possible to have an opposite match at later steps in the backward chaining, for example to match the anti-fact RHS of a strong requirement. We want this to create a mandatory solution also.
This pull request updates the logic in `abduce` to allow the simulation mode to switch to mandatory at steps …
> In abduce, allow switching to SIM_MANDATORY not at the sim root

- r_exec/pattern_extractor.cpp
- r_exec/pattern_extractor.h
When TPX is building a model, it needs an icst for the LHS of a requirement model which contains a candidate prerequisite fact. (It does a search of icsts which are in the input buffer.) TPX uses `find_f_icst_component` to search each of these icst to see if it has a matching component (the candidate prerequisite fact). If found, `find_f_icst_component` [returns the index](https://github.com/IIIM-IS/AERA/blob/3ac45a235e632f93a88ac5efee6ae525d9b06385/r_exec/pattern_extractor.h#L214-L215) of the matching component in the cst list of members. This index [is used](https://github.com/IIIM-IS/AERA/blob/3ac45a235e632f93a88ac5efee6ae525d9b06385/r_exec/pattern_extractor.cpp#L935) to get the `cause_pattern` which is hypothesized to be a needed [parameter potentially …
> TPX find icst component recursion

- r_exec/mdl_controller.cpp
When the model controller makes an assumption, it [adds it to the list of assumptions](https://github.com/IIIM-IS/AERA/blob/584578bcfe95d973328dd1bfc9fae4a01bc3efad/r_exec/mdl_controller.cpp#L2653). When `reduce` is called with an input, it checks the list of assumptions. [The comment](https://github.com/IIIM-IS/AERA/blob/584578bcfe95d973328dd1bfc9fae4a01bc3efad/r_exec/mdl_controller.cpp#L1821) says "ignore home-made assumptions". This makes sense because the model should not make predictions from an assumption that it generated. However, currently the code does not actually ignore the input if it is an assumption. This appears to be an error. Way back in July of 2012, the [code was](https://github.com/IIIM-IS/AERA/blob/4fd3feaeeea6863bfbcb26f050ddc8805bfcbf2b/r_exec/mdl_controller.cpp#L14 …
> In reduce, ignore home made assumptions

- r_exec/mdl_controller.cpp
During simulated forward chaining, a model such as the following (simplified) can fire to predict the consequence of the command on its LHS:
M0:(mdl [H: P0: T0: T1:] []
(fact (cmd move [H: DeltaP:] :) T2: T1_cmd: : :)
(fact (mk.val H: position P1: :) T1_RHS: T3: : :)
In addition to the simulated prediction for the RHS, the controller injects a simulated imdl showing that the model fired with certain template values:
(imdl M0 [h 0 0s:700ms:0us 0s:800ms:0us] [15 15 0s:800ms:0us 0s:900ms:0us])
This imdl can match the LHS of a "reuse" model such as:
M6:(mdl [H: T: P0: T0: T1:] []
(fact (imdl M0 [H: P0: T0_M0: T1_M0:] [DeltaP: P1: T1_RHS: T3:] : :) T0_cmd: T1_cmd: : :)
(fact (mk.val T: position P1: :) T1_RHS: T3: : :)
This reuse model predicts that, under certain preconditions established by a …
> Predict simulated imdl for resuse model

- r_exec/mdl_controller.cpp
- r_exec/pattern_extractor.cpp
The prediction targeted pattern extractor (PTPX) is invoked when a prediction fails. It makes a new model where the RHS is an anti-fact of the imdl which produced the prediction, and the LHS is an icst which explains the conditions of the failure. The purpose of pull request #166 was to make the timings of the RHS imdl match those of the LHS icst so that the resulting "anti-requirement" model does not need guards to adjust the timings:
(mdl |[] []
(fact (icst cst_ball_and_wall_same_position |[] [v0: v1: v2: v3:]) v4: v5:)
(|fact (imdl mdl_ball_position [v0: v1: v3: v4: v5:] [v6: v7: v8:]) v4: v5:)
|[]
|[])
We still want the "anti-requirement" model to look like this, but PR #166 achieved this by altering the timings of the original imdl _at the moment when it was produced_. Normally, when …
> PTPX: In reduce, use the template timings for the RHS. Revert PR #166.

- AERA/replicode_v1.2/hand-grab-sphere.replicode
- r_comp/compiler.cpp
- r_comp/decompiler.cpp
Background: In the Replicode syntax, `[]` is not an empty set. Rather it marks the beginning of set members which are indented on the following lines. To write an empty set, you have to use `|[]`. For example, here is an icst where the template set is empty:
(icst S0 |[] [h 25])
This syntax is unusual, confusing to others during presentations, and a gotcha for new AERA users. If possible, we want to use `[]` .
This pull requests has two commits. The first commit updates the Compiler to allow `[]` as an empty set if it is not at the end of a line. (We also update the Decompiler to write `[]` in the same place.) This is the majority of cases. Now the icst looks as expected:
(icst S0 [] [h 25])
The Compiler still allows `|[]`, so this change is backwards compatible with existing Replicode …
> Compiler: Treat [] as an empty set if it is not at the end of a line

- r_exec/mem.cpp
Background: As the method comment says, `unpack_hlp` produces a new model featuring a set of pattern objects instead of a set of embedded pattern expressions. This is used when [comparing two models](https://github.com/IIIM-IS/AERA/blob/d191299a1087c852a00e6686f4193a685ebde422/r_exec/model_base.cpp#L184-L186) to check if they are equal, for example to check if a new proposed model is the same as one which has already been produced by the pattern matcher. It is necessary to compare the unpacked versions of each.
`unpack_hlp` makes a new buffer `unpacked_hlp` and initially [copies the code](https://github.com/IIIM-IS/AERA/blob/864ea755c7bf903a6284c811ae3950e88cbbb7c5/r_exec/mem.cpp#L1035-L1036) from the packed model into it. It fixes some of the references in this new buffer. The unpacked …
> Fix bug in unpack_hlp: Shift code from unpacked_hlp

- r_exec/mdl_controller.cpp
Background: `PrimaryMDLController::reduce` processes an input for a model controller. If the input is not a goal, it[ calls PrimaryMDLOverlay::reduce](https://github.com/IIIM-IS/AERA/blob/dev/r_exec/mdl_controller.cpp#L1877) to check if the model should make a prediction from the input, and if it does to return true. If it returns false (because no prediction was made), then the model controller [calls monitor_predictions](https://github.com/IIIM-IS/AERA/blob/dev/r_exec/mdl_controller.cpp#L1878) to check if the input matches a previous prediction. It makes sense that we only check the input against previous predictions if we didn't use it to make a new prediction. The model controller also calls `monitor_goals` to check if the input matches a previous goal. Finally, if there are no …
> Monitor goals even if a prediction was made

- r_exec/pgm_overlay.cpp
This pull request fixes the bug in issue #211.
Background: When an object is matched to the pattern in a program, the program controller [calls patch_input_code](https://github.com/IIIM-IS/AERA/blob/4356636b313858fce179c79bfbfd5b901ba73f77/r_exec/pgm_overlay.cpp#L758) which temporarily modifies the program code to place pointers to the input object which has the values that match variables in the pattern. This is a recursive process where `patch_input_code` [calls itself](https://github.com/IIIM-IS/AERA/blob/4356636b313858fce179c79bfbfd5b901ba73f77/r_exec/pgm_overlay.cpp#L652) when there is an `I_PTR` (internal pointer) which has more of the nested structure of the pattern. This requires keeping track of the offset of the substructure of the code being processed. For example, in [this …
> Fix bug in patch_input_code: Use input_code_index when recursing structures

- r_exec/pattern_extractor.cpp
Currently, the method CTPX::get_default_guard_builder can generate reuse models with guards for calculating values for timing variables. A reuse model is a model with an imdl on its LHS. In complex examples, CTPX may need to build reuse models with guards for calculating values for timing variables and other types of variables.
This pull request extends CTPX by updating the CTPX::find_guard_builder method so that if the cause is an imdl, CTPX scans the exposed arguments of that, and checks if the observed value change equals any of the arguments. If so, it creates reuse models with guards for calculating values for timing variables and other types of variables.
> If the LHS cause is an imdl, find_guard_builder can be used

- r_exec/hlp_context.cpp
- r_exec/hlp_overlay.cpp
Background: During backward chaining, the backward assignment guards are evaluated. For example the move model evaluates `DeltaP:(- P1 P0)` . In this case the variable `P0` is bound to the current position and `P1` is bound to the goal position which was determined during backward chaining. Therefore `DeltaP` can be computed. In general it is expected that the variables in the expression are all bound to a value, and that the assignment variable doesn't have a value yet. (This has been the case in all the examples we have worked with so far.)
But now we have a case that comes from reuse models where, during backward chaining, the value of the assignment variable such as `DeltaP` is known, but some of the variable in the expression are unknown. Currently, the code to evaluate backward …
> Don't fail evaluation if assignment guard is already bound

- AERA/replicode_v1.2/hand-grab-sphere.replicode
- r_exec/binding_map.cpp
- r_exec/guard_builder.cpp
- r_exec/guard_builder.h
- r_exec/mdl_controller.cpp
- r_exec/pattern_extractor.cpp
Background: In the hand-grab-sphere example, the reuse model `M6` currently is:
M6:(mdl [H: C: P0: T0: T1:] []
(fact (imdl M0 [H: P0: T0_M0: T1_M0:] [DeltaP: P1: T2: T3:] : :) T0_cmd: T1_cmd: : :)
(fact (mk.val C: position P1: :) T2: T3: : :)
[]
T2:(+ T0 100ms)
T3:(+ T1 100ms)
[]
T0_cmd:(- T1_RHS 80ms)
T1_cmd:(- T3 100ms)
T0:(- T2 100ms)
T1:(- T3 100ms)
T0_M0:(- T2 100ms); Duplicate T0.
T1_M0:(- T3 100ms);     Duplicate T1.
In forward chaining, a goal requirement makes the imdl `(imdl M0 [h 0 0s:200ms:0us 0s:800ms:0us] [: : : :] :)`. This matches the LHS of model `M6` and binds `T0_M0` and `T1_M0` to the timing values 0s:200ms:0us 0s:800ms:0us. Also, the requirement model has stored the requirement `(imdl M6 [h s 0 0s:600ms:0us 0s:700ms:0us] [: : : : : :])`. This matches and the template …
> Support model shared template variables

- INSTALL.md
INSTALL.md does not specify that AERA is 32 bit, which might cause an issue if the build solution is set to 64 bit automatically.
Building AERA also works on newer versions (up to 2022) of VS community, but the required Windows SDK version isn't listed in the installer anymore. Instead you can download it from the Microsoft archive.
> INSTALL: Update SDK options and add Win32

- r_exec/mdl_controller.cpp
- r_exec/mdl_controller.h
Pull request #186 updated `retrieve_simulated_imdl_fwd` to return multiple matches if there are multiple matching requirements. This allows `PrimaryMDLOverlay::reduce` to call `predict` once for each match. The reason we need this is explained in that pull request (in short, because there can be multiple ways to instantiate a model which make different valid predictions from the RHS). Similar arguments apply to the method `retrieve_imdl_fwd`, but at the time we didn't have a use case where there were multiple matching non-simulated requirements. Now we have a use case, so that we can implement the change to `retrieve_imdl_fwd` and test it (for instance, if there are two non-simulated requirements which allow grabbing a sphere or a cube, the grab model should predict both).
Similar to that …
> Multiple matches in retrieve_imdl_fwd

- AERA/IODevices/TCP/Proto/tcp_data_message.pb.cc
- AERA/IODevices/TCP/Proto/tcp_data_message.pb.h
- AERA/IODevices/TCP/Proto/tcp_data_message.proto
- AERA/IODevices/TCP/Proto/utils.h
- AERA/IODevices/TCP/tcp_io_device.cpp
Added a COMMUNICATION_ID message type to the protobuf messages and a handler that injects entities with the sent communication id into AERA accordingly.
Tested by sending "h holding ..." to AERA with cube, sphere, and "nothing". The casting of bitstreams to the according communication id and transforming to AERA internal OIDs works in the given cases.
> Added support of sending entities to AERA

- r_exec/mdl_controller.cpp
Background: A model can have associated weak and strong requirement models. During forward or backward chaining, these can instantiate strong or weak requirements. If there is a matching weak requirement, then the model can be instantiated, but if there is also a matching strong requirement then this prevents it being instantiated. ("Being instantiated" means that if there is a matching LHS then the model can fire.) The method `retrieve_imdl_fwd` examines the weak and strong requirements which are attached to a model and returns the "chaining status" which can be [one of the following](https://github.com/IIIM-IS/AERA/blob/75db7506a489bd57727e5cbdfa820c6d99624d95/r_exec/hlp_controller.h#L90-L94):
WEAK_REQUIREMENT_DISABLED
STRONG_REQUIREMENT_NO_WEAK_REQUIREMENT …
> Return NO_REQUIREMENT if only strong requirements but none match

- r_exec/mdl_controller.cpp
The pull request resolves issue #245. See that for background. As expected, the information of grabbing the cube (not the sphere) wasn't being carried through to PTPX. This information is created by the controller for the grab model which[ calls predict](https://github.com/IIIM-IS/AERA/blob/c2e737a87b45bf24cd37ad145781eb8bdd3253e4/r_exec/mdl_controller.cpp#L190) twice in a loop, to predict grabbing the cube on the first iteration and to predict grabbing the sphere on the second iteration. The problem is that the code [reuses one copy](https://github.com/IIIM-IS/AERA/blob/c2e737a87b45bf24cd37ad145781eb8bdd3253e4/r_exec/mdl_controller.cpp#L189) of `f_imdl`, so that on the second iteration the `imdl` with the information for the cube is replaced by the information for the sphere. The …
> In reduce, copy f_imdl before calling predict

- r_exec/mdl_controller.cpp
- r_exec/mdl_controller.h
Background: Pull requests #186 and #243 allow matching multiple requirements during forward chaining. Usually the requirements have different parameters, so they make different predictions. But there can be duplicate predictions (especially if two models were learned that make the same predictions.) Duplicate predicted facts can result in duplicate predicted composite states, and these can produce further duplicates (especially during simulated forward chaining). We want to avoid a snowball effect.
This pull request updates the `predict` method to add a parameter `already_predicted`. The caller creates an empty list and passes it each time it calls `predict`. If the new prediction is not in the list, then it is injected and added to the list. If the new prediction is already in the list, …
> In predict(), avoid injecting already predicted

- AERA/replicode_v1.2/std.replicode
- r_exec/binding_map.cpp
- r_exec/binding_map.h
- r_exec/init.cpp
- r_exec/mdl_controller.cpp
- r_exec/mdl_controller.h
- r_exec/opcodes.cpp
- r_exec/opcodes.h
- r_exec/pattern_extractor.cpp
This pull request resolves #137 by adding support for time intervals as `(ti after before)` with "smart matching" for intersecting time intervals. It also resolves #251 because the "smart matching" updates ti value in the imdl which remains when the imdl is injected.
This pull request has six commits. The first commit changes `init_from_ihlp_args` which assigns variables in the binding map to template args from an ihlp (an imdl or icst). The current implementation gets the size of the template args and just assumes that the variables are in sequence starting from `v0`. For example `(imdl M2 [h s 100ms 200ms] ...)` has four template args for model `M2` which is:
M2:(mdl [v0: v1: v2: v3:]
...
Therefore, the current implementation just assumes that the template args in the imdl should be …
> Implement time interval (ti after before)

- AERA/AERA.vcxproj
Finally found the setting to change the vcpkg configuration to use debug dlls instead of release. It works on my machine after "Clean Solution" and "Rebuild Solution". Can you confirm this?
> Changed vcpkg configuration to use correct dlls in debug

- r_exec/binding_map.cpp
Background: A binding map stores values in subclasses of `BoundValue`. The `StructureValue` is used to store the bound value of a structured object such as `(vec3 1 2 3)`. The `copy_structure` method of `StructureValue` copies the code of a structure into and out of an AERA object such as `(mk.val h postition (vec3 1 2 3))` .
We want to support a bound value of a "nested" structure object such as `(vec [1 2 3])`, where the `(vec :)` is the top structure and the array `[1 2 3]` is the sub structure. This pull request updates `copy_structure` to check if part of the structure is an I_PTR which points to a sub structure. If so, then it calls itself recursively to copy the sub structure (and any further sub-structures). There is no change of behavior for existing AERA examples where no bound …
> StructureValue: recursive copy of sub-structures

- r_exec/factory.cpp
Background: The method [`MatchStructure`](https://github.com/IIIM-IS/AERA/blob/c8935633a635a740844b12cfe42652b8fb0f4193/r_exec/factory.cpp#L349) has a parameter `lhs_base_index` which is passed on to the [call to `Match`](https://github.com/IIIM-IS/AERA/blob/c8935633a635a740844b12cfe42652b8fb0f4193/r_exec/factory.cpp#L361) which scans the structure by incrementing `lhs_index`. If `Match` comes across an I_PTR, then it recursively [calls `MatchStructure`](https://github.com/IIIM-IS/AERA/blob/c8935633a635a740844b12cfe42652b8fb0f4193/r_exec/factory.cpp#L294) where the `lhs_base_index` is the position of the new structure, and where 0 is again passed for `lhs_index`.
`MatchStructure` is also [called from `CounterEvidence`](https://github.com/IIIM-IS/AERA/blob/c8935633a635a740844b12cfe42652b8fb …
> Fix bug in CounterEvidence call to MatchStructure

- r_exec/binding_map.cpp
- r_exec/binding_map.h
Background: `BindingMap::abstract_f_ihlp` is used to convert an icst or imdl into an abstract version by replacing each reference to a variable. For example, with the following "non-abstract" input:
(icst cst_147 [] [h s] false 1)
`abstract_f_ihlp` makes this abstract result:
(icst cst_147 [v0: v1:] [v0: v1:] undefined 1)
The exposed args list `[h s]` is correctly abstracted to `[v0: v1:]` . But this is incorrectly used to overwrite the template args which should be `[]` as in the original. This is due to a bug. After writing the template args structure we need to increment extent_index by `1 + tpl_arg_count` , not just by `tpl_arg_count` . 
There is another error. In the original, weak requirement enabled is `false` , but this is not copied through. We fix this similar to the other copy …
> BindingMap: Fix bug in abstract_f_ihlp template args

- AERA/AERA.vcxproj
- AERA/AERA.vcxproj.filters
- AERA/NatvisFile.natvis
Natvis is a way to visualize the debugger information at the bottom of the screen of Visual Studio. With this, the way Atoms are displayed is much more helpful that the standard uint32 display.
You can see all important things with a quick glance, like OpCode (if needed), descriptor, index, and so on.
For a single Atom, this isn't that much helpful, but it is also shown in r_code::Code objects.
> Created new Natvis file for better debugging display

- r_exec/binding_map.cpp
- r_exec/binding_map.h
Background: When a new cst or model is injected, a controller is created for it. The controller has a "binding map template" which is simply a binding map with the same number of variables as the cst or model. The controller's binding map template is set up by `HLPBindingMap::init_from_hlp` which scans the code of the cst or model looking for variables. Consider this cst (simplified):
(cst [] []
(fact (mk.val v0: holding []) v1: v2:)
(fact (icst cst_same_pos [] [v0: v3: v4: sphere]) v1: v2:))
It has variables `v0` through `v4` so the binding map template should have these five variables.
More background: A cst or mdl has a "packed" and "unpacked" version. The packed version has all the code in one array similar to the example shown above. There can be external references such as …
> HLPBindingMap: In init_from_hlp, add packed_hlp and use it to get vars

- r_exec/mdl_controller.cpp
- r_exec/mdl_controller.h
Pull request #250 implemented the `(ti after before)` time interval structure which we now use for the template timings. That updated the method `get_imdl_template_timings` to optionally handle this as well as the previous method of two separate timestamps (without `ti`) for backwards compatibility. Now that we have updated all of the hand-coded models in the seed code and examples (and the CTPX model builder now uses `ti`), we don't need the backwards compatibility. Also, the `TemplateTimingsUpdater` class is not needed because "smart matching" of timings is now done automatically for `ti` values (as explained in PR #250).
This pull request removes the unneeded `TemplateTimingsUpdater` class and simplifies `get_imdl_template_timings` because it only needs to work with the `ti` value.
> Remove unneded TemplateTimingsUpdater

- AERA/replicode_v1.2/std.replicode
- r_code/utils.h
- r_exec/cst_controller.h
- r_exec/mem.h
Background: In pull request #71, we changed to distinguish int values for `Timestamp` from duration in `std::chrono::microseconds`. This works, but the `Timestamp` type uses `std::chrono::system_clock` which does not use microseconds internally. Instead it uses units of the system clock "tick" where each tick period is 100 nanoseconds. This means that each math operation between a `Timestamp` and a duration in microseconds requires converting between the two different representations. This is done automatically by the compiler, but it is not desirable. There can be loss of accuracy and the `Timestamp` does not hold the full precision of the 64-bit microseconds value.
Fortunately, the C++ standard library is parameterized and I noticed that it is easy to control the `Timestamp` …
> Use microseconds for Timestamp period

- AERA/AERA.vcxproj
- INSTALL.md
- output_window/output_window.vcxproj
- r_code/r_code.vcxproj
- r_comp/r_comp.vcxproj
- r_exec/r_exec.vcxproj
- usr_operators/usr_operators.vcxproj
Currently, AERA builds which Visual Studio 2017 and 2019, but does not build on the latest Visual Studio 2022. This because AERA uses Windows SDK 10.0.17134.0, which is outdated and not available in Visual Studio 2022, which what most newcomers will install. (It's possible to do a special download and get it running in Visual Studio 2022 but this is difficult to install.)
This pull request updates the project files to change from SDK 10.0.17134.0 to 10.0.18362.0, which is available in Visual Studio 2022 and 2019. (Visual Studio 2017 will not be supported.) We also simplify the README because it's now possible to use the default Visual Studio download (instead of an archive download).
> Change to SDK 10.0.18362.0 (to support VS 2022). 

- r_exec/p_monitor.cpp
The Webots example has the following model (simplified):
mdl_displace_hand:(mdl [H: P0: (ti T0: T1:)] []
(fact (cmd move [H: (vec3 0.5 0 0)] :) T0_cmd: T1_cmd: : :)
(|fact (mk.val H: position P0: :) T2: T3: : :))
Note that the RHS is an anti-fact. This model was created to use in backward chaining where the goal is for the hand H to not be at a position (so that a particular composite state will not hold). The model says "If the hand H has position P0 and the goal is to not have position P0, then move the hand by 0.5". This works great for achieving that goal.
The problem is that this model may also be instantiated in forward chaining. For example, during babbling sometimes the hand moves by 0.5. This model makes a prediction of the RHS which is the prediction of the anti-fact: If the …
> Prediction monitor: In update, only register a failure for predicted fact

- r_exec/factory.cpp
Background: `is_evidence` is used to check if a fact is evidence for a target. If two objects have the same object/property but different values, then this is called "counter-evidence" for example consider:
target:   (fact (mk.val h position 5))
evidence: (fact (mk.val h position 10))
If the target position is 5 but the evidence is that the position is 10, then this is counter-evidence. In this case, `is_evidence` returns `MATCH_SUCCESS_NEGATIVE`. (This is different than `MATCH_FAILURE` which means that the two facts are unrelated.)
But now consider if the target is an anti-fact:
target:   (|fact (mk.val h position 5))
evidence: (fact (mk.val h position 10))
The target was to not have position 5, and the evidence is that the position is 10, which is not 5. The target was achieved! The …
> In is_evidence, fix is evidence for anti fact target

- r_exec/ast_controller.tpl.cpp
- r_exec/auto_focus.cpp
Background: When the input to the auto focus controller is a mk.val like `(mk.val h position 10)` it creates an AST controller for it. AST means "atomic state" and is used to track if a state variable changes. In the next frame, if the input to the auto focus controller is another mk.val like `(mk.val h position 15)`, then it will invoke CTPX to try to find a model that explains the change. However, if the input to the auto focus controller is a prediction that matches the target of an AST controller, then this means that there is already a model that is making predictions for it and we don't need to invoke CTPX again. In this case the AST controller is canceled. 
Now we are doing experimentation with anti-facts, including models which predict anti-facts. The existing code seems to assume …
> Don't use CTPX for anti-facts

- r_exec/binding_map.cpp
We want to be able to make a model like this:
mdl_displace_hand:(mdl [H: P0: (ti T0: T1:)] []
(fact (cmd move [H: DeltaP:] :) T2: T1_cmd: : :)
(|fact (mk.val H: position P0: :) T1_RHS: T3: : :)
[]
T1_RHS:(+ T0 100ms)
T3:(+ T1 100ms)
[]
T2:(- T1_RHS 80ms)
T1_cmd:(- T3 100ms)
T0:(- T1_RHS 100ms)
T1:(- T3 100ms)
DeltaP:(vec3 -0.5 0 0))
Notice that the value of an assignment guard is usually an operator like `(- T3 100ms)` in the assignment for `T1`. But notice that the value of the assignment for `DeltaP` is the literal `(vec3 -0.5 0 0)`. Currently, the AERA code assumes that the value of an assignment guard is always the result of evaluating an operator. But we want to allow an object literal.
This pull request updates `BindingMap::bind_variable` to allow the value to be a structured object …
> Allow assignment guards to bind an object literal

- AERA/Demo1/std.replicode
- AERA/replicode_v1.2/std.replicode
- r_exec/init.cpp
- r_exec/opcodes.cpp
- r_exec/opcodes.h
- r_exec/operator.cpp
- r_exec/operator.h
Similar to PR #279, we want to be able to make a model like this:
mdl_displace_hand:(mdl [H: P0: (ti T0: T1:)] []
(fact (cmd move [H: DeltaP:] :) T2: T1_cmd: : :)
(|fact (mk.val H: position P0: :) T1_RHS: T3: : :)
[]
T1_RHS:(+ T0 100ms)
T3:(+ T1 100ms)
[]
T2:(- T1_RHS 80ms)
T1_cmd:(- T3 100ms)
T0:(- T1_RHS 100ms)
T1:(- T3 100ms)
DeltaP:5
In this case the fixed value for `DeltaP` is just the number 5. The problem is that Replicode syntax doesn't allow `DeltaP:5`. (The opcode for an assignment guard is similar to I_PTR and must point to a structure value.)
As a solution, this PR adds the identity operator `(id X)` which just returns the value `X`. Now, the guard can be `DeltaP:(id 5)` which is valid syntax.
> Add the identity operator (id X)

- AERA/replicode_v1.2/std.replicode
- r_code/replicode_defs.h
- r_exec/factory.cpp
- r_exec/factory.h
- r_exec/mdl_controller.cpp
- r_exec/mdl_controller.h
- r_exec/p_monitor.cpp
Background: Currently the success object is defined as:
(success obj evidence)
where `obj` is a goal or prediction, and `evidence` is a fact which shows that the goal or prediction is achieved. (Alternatively, if the success object is linked from an anti-fact then it shows failure and `evidence` is the contradicting fact.) Take the case when `obj` is a prediction from a model like `(fact (pred (fact (mk.val h position 5))))` . In the next frame, the evidence `(fact (mk.val h position 5))` is observed, and a success object is injected with these values.
Note that the model made a prediction based on an actual LHS like `(fact (cmd move [h -20]))`, along with a requirement which contains the prerequisite environment state. This is all contained in the reduction marker which is already …
> success object: Add optional obj_mk_rdx

- r_exec/factory.h
Background: A drive is a fact where the object is a simple token like `run`. For example, `(fact run 1s:400ms:0us 2s:0ms:0us 1 1)`. Currently, the method `is_drive` checks that a goal is drive if it is not a simulation, and that the actor is `self`. But it doesn't make sure that the object is a token like `run`.
This pull request adds this check to `is_drive`. (The way to check is because the object is defined as an `Ent`. This same check is [made elsewhere](https://github.com/IIIM-IS/AERA/blob/4436fe13458e46b1f54238024db8ce3cd923b24c/r_exec/mdl_controller.cpp#L304) too.)
Details on why this hasn't been an issue before now: Most goal objects are simulated goals during simulated backward chaining. Non-simulated goals are usually drives that are handled in `TopLevelMDLController::reduce`. …
> In is_drive, also check for Ent

- r_exec/g_monitor.cpp
- r_exec/pattern_extractor.cpp
Background: We inject a goal of an anti-fact such as `(goal (|fact (mk.val h position 5)))`. Later, a fact is injected which satisfies the goal such as `(fact (mk.val h postition 10))` . The goal monitor calls `register_goal_outcome` to inject a `success` object which indicates that the goal was (unexpectedly) achieved, and this is intercepted by GTPX which tries to make a model to explain the unexpected success. The success object is supposed to have everything that GTPX needs to make the model (but it doesn't - see below).
In the same frame but slightly later, there is already a model which predicts the goal-satisfying fact such as `(fact (mk.val h postition 10))` . When the actual fact is injected, AERA injects a success object like `(success f_prediction evidence prediction_mk_val)` …
> GTPX: Build anti-fact model in ack_pred_success

- r_exec/pattern_extractor.cpp
As explained in pull request #285, when the goal is an anti-fact then `GTPX::ack_pred_success` gets important items from the reduction marker of the prediction success object and calls `build_mdl` to build the causal model and requirement model. One of these important items is the input to the requirement model which made the prediction (the LHS of the requirement model). This is an icst like `(fact (icst S0 [] [h 5]))` . Normally, `build_mdl` tries to build a new cst for the requirement model, but in this case we want it to use the one which made the prediction.
This pull request updates `GTPX::build_mdl` to use an existing icst (if provided) to build the requirement model in conjunction with the GTPX causal model. Otherwise, this is similar to `CTPX::build_mdl` and in fact calls the …
> GTPX: Update build_mdl for anti-fact and given icst

- r_exec/binding_map.cpp
In the 'contains(...)' method called during intersect of two binding maps, when the checked for code object is an object consisting of floats, only the first one was compared to assess whether they are the same. Now it checks all fields of objects that are floats and only returns true when all parts of both sides are the same.
> Minor code change to fix bug when intersecting two binding maps

- AERA/IODevices/TCP/tcp_io_device.h
This allows building with ENABLE_PROTOBUF isn't defined.
> tcp_io_device.h: Move socket includes into ENABLE_PROTOBUF section

- r_comp/preprocessor.cpp
The Replicode spec says that a comment ending in " .." is continued to the next line. The preprocessor handles this and checks for "..". But it also treats a single space as a comment continuation. This causes problems since it is common for a comment to end in a space (since it's difficult to see in the text editor). This appeared as a problem in Linux where the end of line is just a newline (not like carriagereturn/newline in Windows). The handling of end of lines is a [separate issue](https://github.com/IIIM-IS/AERA/issues/293). This PR simply changes the preprocessor to not treat an ending space as a comment continuation.
> r_comp: Don't treat trailing space as comment continuation
